### ISSUE TITLE
FutureWarning for the way a None object is checked

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/MementoEmbed#40] opened 2018-06-14 17:19 UTC
After booting the server when the first card creation request arrives, the server logs a warning.

```
/app/mementoembed/mementosurrogate.py:785: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if maxpara:
```

**Comment by ibnesayeed** [comment] 2018-06-14 17:22
https://stackoverflow.com/questions/18583162/difference-between-if-obj-and-if-obj-is-not-none

**Comment by shawnmjones** [comment] 2018-06-14 17:30
Duplicate of #39

**Closed by shawnmjones** 2018-06-14 17:30 UTC
Labels: duplicate, enhancement

**Comment by ibnesayeed** [comment] 2018-06-14 17:34
I think we both were creating the ticket and patching it at the same time, because this time I did check for any existing tickets before opening a new one. ;-)

**Comment by shawnmjones** [comment] 2018-06-14 17:36
I've been fixing warnings that have been polluting my unit test output. The fact that you noticed them in the log of the actual application makes me feel like my decision to eliminate these "irritants" was the correct one.
