### ISSUE TITLE
First attempt to create a card fails

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/MementoEmbed#35] opened 2018-06-13 23:32 UTC
Run the server and load the page `http://localhost:5550/` then enter a URI-M and click "Create a Social Card" button. For the first time the card creation request is not processed, instead the page is redirected to `http://localhost:5550/?#` (notice the added `?#` part in the URL), the form is cleared, and a message is logged in the console, saying `we have failure with data: [object Object]`. Any further attempts will be processed as expected (unless the `?#` is removed from the URL again.)

**Comment by shawnmjones** [comment] 2018-06-14 02:11
Duplicate of #9.

**Closed by shawnmjones** 2018-06-14 02:11 UTC
Labels: bug, duplicate
